version: "3.6"
services:
  background:
    container_name: remover
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./images:/usr/src/app/images
      - ./output:/usr/src/app/output
      - ./models/u2net.pth:/root/.u2net/u2net.pth
      - ./cli.py:/usr/src/app/cli.py
    command: |
      sh -c '''
      cd /usr/src/app && python3 cli.py \
      -af 10 \
      -wn 8 \
      -i "images/20210313_IMG_3816.jpg" \
      -o "output/test.png"
      '''
    # restart: always

volumes:
  models:
  images:
  output: